version: "2"
services:
    web:
      build: .
      volumes:
        - .:/code
      ports:
        - "80:8080"
      links:
        - db:mongo
    db:
      image: mongo
      ports:
        - "27017:27017"
