version: "2"
services:
    web:
      build: .
      volumes:
        - .:/code
      ports:
        - "80:8080"
      links:
        - db:mongo
    db:
      image: mongo
      ports:
        - "27017:27017"
      networks:
            vpcbr:
              ipv4_address: 10.5.0.5
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
