web:
  build: .
  volumes:
    - .:/code
  ports:
    - "80:8080"
  links:
    - db
db:
  container_name: mongo
  image: mongo:latest
  ports:
    - "27017:27017"
networks:
    default:
        driver: custom-driver-1
