server:
  port: 8080
spring:
  data:
    mongodb:
      host: 10.5.0.5
      port: 27017
#      host: 192.168.99.100
#      port: 28018
      database: safe
x-auth-token: EzCXxjmQMjxBdQaNHbyiZwoiwrFdnyxXQqKnNywJ3JwL
service:
  url:
    weather: https://d1fuzbayh0.execute-api.eu-central-1.amazonaws.com/prod/weather
    crypto: http://rest.metraf.eu/prices
